services:
  server:
    container_name: server
    tty: true
    build: ./server
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22
      - 3306
    ports:
      - "80:80"

  database:
    container_name: database
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123@
      - MYSQL_DATABASE=ssh_cmd_exec_api
      - MYSQL_USER=server
      - MYSQL_PASSWORD=server123@
    volumes:
      - ssh_cmd_exec_api_database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ssh_cmd_exec_api_network
    ports:
      - 3306

  client:
    container_name: client
    tty: true
    build: ./client
    environment: 
      - USER client
      - PASSWORD client
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22

  client2:
    container_name: client2
    tty: true
    build: ./client
    environment: 
      - USER client2
      - PASSWORD client2
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22
    
  client3:
    container_name: client3
    tty: true
    build: ./client
    environment: 
      - USER client3
      - PASSWORD client3
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22

  client4:
    container_name: client4
    tty: true
    build: ./client
    environment: 
      - USER client4
      - PASSWORD client4
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22

  client5:
    container_name: client5
    tty: true
    build: ./client
    environment: 
      - USER client5
      - PASSWORD client5
    networks:
      - ssh_cmd_exec_api_network
    expose:
      - 22

networks:
  ssh_cmd_exec_api_network:
    driver: bridge

volumes:
  ssh_cmd_exec_api_database:
